[code-projects] don't call styler func for chunks on empty DataFrame/Series
Fixes the problem discovered in the "test_apply" tests:

 ValueError: Function <...> resulted in the apply method collapsing to a Series.
 Usually, this is the result of the function returning a single value, instead of list-like.